schema_version: 1.0.0
themes:
  - name: Light
    background: "#FFFFFF"
    text: "#000000"
    primary: "#31A247"
    secondary: "#7285BF"
    accent: "#CB5F66"
  - name: Dark
    background: "#000000"
    text: "#FFFFFF"
    primary: "#837BA4"
    secondary: "#CB5F66"
    accent: "#F3D35E"
charts:
  - hex: "#F3D35E"
  - hex: "#F48A4E"
  - hex: "#F5403D"
  - hex: "#CB5F66"
  - hex: "#837BA4"
  - hex: "#4d6ac3"
  - hex: "#46b85d"
  - hex: "#31A247"
status_indicators:
  - name: Success
    color: "#31A247"
  - name: Warning
    color: "#F48A4E"
  - name: Error
    color: "#F5403D"
branding:
  logo:
    primary_color: "#CB5F66"
    secondary_color: "#837BA4"
    accent_color: "#4d6ac3"